name: Docs PR previews

concurrency: preview-${{ github.ref }}

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions: 
  contents: write
  pull-requests: write
  issues: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch jsdoc theme

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - run: npm ci
      - run: npm run docs
        if: github.event.action != 'closed'
        
      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./docs
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
